### ISSUE TITLE
key: value support of data mapping in non-yaml secrets

### ISSUE THREAD

**Issue by notandy** [justwatchcom/gopass#638] opened 2018-01-21 23:58 UTC
Hey,

I just moved from browserpass to gopassbridge and experienced that login/email/username key: value in the body part of the secret doesn't work anymore. A lot of software like Android/IOS/Browserpass/etc pass compatible software uses the naive key: value metadata description.

I've seen gopass json api only provides metadata if the secret is stored in yaml format. I have successfully implemented a very easy key: value parser to fill the data map of the secret datatype if yaml parsing fails.
see https://github.com/notandy/gopass

But yaml is really tightly integrated, I am not sure how cleanly implement the classical approach in parallel. My implementation breaks tests and expectations.

As of #559 the yaml support itself is quite buggy, even though I appreciate the work invested having yaml support in gopass, I would really like seeing the yaml parser dropped and  instead having a basic key: value parser. (which should also be able to parse the yaml key/value entries)

**Comment by dominikschulz** [comment] 2018-01-22 07:45
As state in #559 I'm aware of these issues and I would like to improve the situation. Moving to a simple key:value parser would solve some of these issue and I like the idea, but it would break a lot of stuff in other places. So the problem is not so much the implementation but rather the migration path.

**Closed** 2018-02-21 14:47 UTC
Labels: enhancement

**Comment by notandy** [comment] 2018-02-21 15:39
:+1:
