### ISSUE TITLE
Error when inserting

### ISSUE THREAD

**Issue by jfeilbach** [justwatchcom/gopass#52] opened 2017-02-13 21:20 UTC
When I attempt to insert new entry I get the following errors:
```
Enter password for foo/bar: 
Failed to restore terminal: errno 0
Retype password for foo/bar: 
Failed to restore terminal: errno 0
gopass: Encrypting foo/bar for these recipients:
 - 0x56333C1D33F8CE08 - foo bar (foo@bar.com) <foo@bar.com>

Do you want to continue? [Y/n]: y

You need a passphrase to unlock the secret key for
user: foo bar (foo@bar.com) <foo@bar.com>"
4096-bit RSA key, ID 33F8CE08, created 2017-02-13

error: gpg failed to sign the data
fatal: failed to write commit object

Error: failed to commit files to git: exit status 128
```
I tried https://www.justwatch.com/gopass/faq/
This did not help. 

My .gitconfig and user definition for my key match as well.

**Comment by metalmatze** [comment] 2017-02-13 22:07
This is a duplicate of #13.

**Closed by metalmatze** 2017-02-13 22:07 UTC
