### ISSUE TITLE
Undocumented : how to add recipient to a sub store ?

### ISSUE THREAD

**Issue by frntn** [justwatchcom/gopass#211] opened 2017-07-21 11:22 UTC
Hello,

This issue is not a bug report but a question.
I can't find how to add recipients to sub stores

For now I temporarly change the `path` key in the config.yml to point to the sub store I want to add recipients to.
I know this is not ideal but it does the job :)

Thanks

**Comment by dominikschulz** [comment] 2017-07-21 11:24
Actually there is a `--store` parameter to most commands, i.e. `gopass recipients add --store=foo john@doe.com`.

We know this isn't very well documented. We'll try to improve the docs soon.

Duplicate of #200

**Comment by ben0x539** [comment] 2017-07-29 09:23
Are you confident this works correctly? When I say `gopass recipients add --store=foo bar`, it seems to mutate the main store and not the named store.

**Comment by dominikschulz** [comment] 2017-07-29 20:20
That would be a bug. Will try to reproduce.

**Comment by ben0x539** [comment] 2017-07-30 06:52
Looks like my problem was that I was passing paths and not mountpoints as the value to `--store=`. Whoops.

**Comment by dominikschulz** [comment] 2017-07-30 20:25
We could try to handle that better. Either infer the mountpoint or are least warn.

**Comment by dominikschulz** [comment] 2017-08-08 14:30
Can not reproduce with that latest master anymore. We made some change to the way mountpoints are matched in #240 .

**Closed by dominikschulz** 2017-08-08 14:30 UTC
Labels: documentation
